### ISSUE TITLE
I have some EOSdac tokens on decentralized exchange,is it locked there forever?

### ISSUE THREAD

**Issue by NeoOntology** [eosdac/conversion#1]
Ы

**Comment by ghost** [comment]
I don't see a solution for recovering these tokens. You'll need the private key of the address on which the tokens are and that is not the case if your tokens are in a contract (ie contracts don't have private keys).

**Comment by NeoOntology** [comment]
Are they going to be unlocked soon? Can I transfer it to my eth address and convert it some other way?

**Comment by ghost** [comment]
No, the eosdac token contract doesn't allow any transfers any more. All eosDAC and EOS can not be transfered to other addresses. I'm sorry, there are no loopholes to change this.

**Comment by NeoOntology** [comment]
Funny start for integrated system.. The smart-contract eth addresses were not registered by anyone with a bunch of airdropped and deposited tokens, they should be considered lost and recovered some other way. Isn't it fair?

**Comment by ghost** [comment]
the problem with smart contracts that hold eos or eosdac is that you can't proof that it is yours. Of course you have the contract creator, but giving all those eos/eosdac to the creator isn't fair neither because it is not his but yours. I'll close this issue.
